---
title: "GBIF overlaps"
author: "Natalie Cooper"
date: "7 March 2019"
output: html_document
---

```{r, echo = FALSE, message = FALSE}
# Load libraries
library(tidyverse)
library(viridis)
library(knitr)
#library(sf)
library(maptools)
library(rgdal)
library(sp)
library(raster)
library(rworldmap)
library(rgeos)
library(spatstat)
library(ggmap)
library(here)

# Short function to get decades
floor_decade <- function(x){
  if(!is.na(x)){
    x - x %% 10
  }else{NA_character_}
}

# Convex hulls function...
make.hull <- function(data){
  hull <- spatstat::convexhull.xy(data$decimallongitude, data$decimallatitude)
  data.frame(x = hull$bdry[[1]]$x, y = hull$bdry[[1]]$y)
}

# Convert SpatialPolygonsDataFrame to dataframe for plotting
convert.spdf <- function(map) {
  map@data$id <- rownames(map@data)
  map.points <- fortify(map, region = "id")
  map.df <- dplyr::full_join(map.points, map@data, by = "id")
  return(map.df)
}
```

First we need to wrangle the GBIF data so only specimens with lat longs and full species names are included, we also add a "clade" variable to deal with fishes being in different classes.
```{r, echo = FALSE, message = FALSE}
# Read in the GBIF data
gbif <- read_csv(here("data/all-gbif.csv"))

# Wrangle the data so it is useable
gbif2 <- 
  gbif %>%
  
  # Check that all included records are specimens not observations
  filter(basisofrecord == "PRESERVED_SPECIMEN") %>%
  
  # Create a new column for specimen ID number
  unite(col = specID, `institutioncode`, `catalognumber`, 
        sep = "_", remove = FALSE) %>%
  
  # Remove post 1900 records and those with no year
  filter(year < 1901 & !is.na(year))  %>%

  # Add decade variable (function above)
  # This maps to character to deal with NAs so needs coercing back to numeric
  mutate(decade = map_chr(year, floor_decade)) %>%
  mutate(decade = as.numeric(decade)) %>%

  # Add clade column, remove sea squirts and make a "fishes" "clade"
  filter(class != "Ascidiacea" & class != "Thaliacea" & !is.na(class)) %>%
  mutate(clade = class) %>%
  mutate(clade = if_else(clade == "Amphibia", "Amphibians", clade)) %>%
  mutate(clade = if_else(clade == "Reptilia", "Reptiles", clade)) %>%
  mutate(clade = if_else(clade == "Aves", "Birds", clade)) %>%
  mutate(clade = if_else(clade == "Mammalia", "Mammals", clade)) %>%
  mutate(clade = if_else(clade == "Actinopterygii", "Fishes", clade)) %>%
  mutate(clade = if_else(clade == "Cephalaspidomorphi", "Fishes", clade)) %>%
  mutate(clade = if_else(clade == "Elasmobranchii", "Fishes", clade)) %>%
  mutate(clade = if_else(clade == "Leptocardii", "Fishes", clade)) %>%

  # Remove records with no lat/long
  filter(!is.na(decimallatitude) & !is.na(decimallongitude)) %>%
  
  # TAXONOMY (note there is a second set of checks later)
  # 1. Remove entries where we only have the Genus
  # 2. Create binomial column
  separate(species, c("Genus", "Species"), sep = " ", 
           extra = "drop", fill = "right") %>%
    filter(!is.na(Species) & Species != "sp." & Species != "sp") %>%
    unite("binomial", Genus, Species, sep = " ") %>%

  # Select just the columns of interest
  dplyr::select(specID, binomial, clade, class, order, family, genus,
           year, decade, decimallongitude, decimallatitude) %>%
  
  # Remove duplicates
  distinct()

# Remove gbif
rm(gbif)
```

```{r}
# Read in maps
maps_amphibian <- readOGR("data/AMPHIBIANS")
maps_mammal <- readOGR("data/MAMMALS")
#maps_bird <- readOGR("data/BIRDS")
```

```{r, echo = FALSE}
# First find only those species with >= 3 specimens with unique localities
specimen3 <- 
  gbif2 %>%
  distinct(clade, binomial, decimallongitude, decimallatitude) %>%
  group_by(clade, binomial) %>%
  summarise(n = n()) %>%
  filter(n >= 3)

# Then select these specimens from the gbif data
gbif3 <- gbif2[gbif2$binomial %in% specimen3$binomial, ]
```


```{r, echo = FALSE}
# Split by clade
gbif3_amphibian <- 
  gbif3 %>%
  filter(clade == "Amphibians")

gbif3_bird <- 
  gbif3 %>%
  filter(clade == "Birds")

gbif3_mammal <- 
  gbif3 %>%
  filter(clade == "Mammals")
```


```{r}
# Create convex hulls for all species with >= 3 unique localities
hull_species_amphibian <- list()
hull_species_bird <- list()
hull_species_mammal <- list()

# Make hulls                              
for(i in 1:length(unique(gbif3_amphibian$binomial))){
  hull_species_amphibian[[i]] <- make.hull(gbif3_amphibian[gbif3_amphibian$binomial ==         
                                                          unique(gbif3_amphibian$binomial)[i], ])
}

for(i in 1:length(unique(gbif3_bird$binomial))){
  hull_species_bird[[i]] <- make.hull(gbif3_bird[gbif3_bird$binomial ==         
                                                unique(gbif3_bird$binomial)[i], ])
}

for(i in 1:length(unique(gbif3_mammal$binomial))){
  hull_species_mammal[[i]] <- make.hull(gbif3_amphibian[gbif3_amphibian$binomial ==         
                                                        unique(gbif3_mammal$binomial)[i], ])
}

# Add species names
names(hull_species_amphibian) <- unique(gbif3_amphibian$binomial)
names(hull_species_bird) <- unique(gbif3_bird$binomial)
names(hull_species_mammal) <- unique(gbif3_mammal$binomial)
```

```{r, echo = FALSE}
# Convert to spatial points dataframe
dsSPDF_amphibian <- SpatialPointsDataFrame(gbif3_amphibian[, c(10,11)], 
                                           data.frame(gbif3_amphibian[, 1:11]),
                                           proj4string = CRS("+proj=longlat +datum=WGS84 
                                                              +no_defs +ellps=WGS84 
                                                              +towgs84=0,0,0"))

dsSPDF_bird <- SpatialPointsDataFrame(gbif3_bird[, c(10,11)], 
                                           data.frame(gbif3_bird[, 1:11]),
                                           proj4string = CRS("+proj=longlat +datum=WGS84 
                                                              +no_defs +ellps=WGS84 
                                                              +towgs84=0,0,0"))

dsSPDF_mammal <- SpatialPointsDataFrame(gbif3_mammal[, c(10,11)], 
                                           data.frame(gbif3_mammal[, 1:11]),
                                           proj4string = CRS("+proj=longlat +datum=WGS84 
                                                              +no_defs +ellps=WGS84 
                                                              +towgs84=0,0,0"))

```

```{r}
# Loop to extract overlaps
# Will write functions for this at some stage

# Create arrays for results
overlaps_amphibian <- array(NA, dim = c(length(unique(dsSPDF_amphibian@data$binomial)), 4))
colnames(overlaps_amphibian) <- c("Binomial", "NumberTypes", "NumberOverlaps", "PercentOverlaps")
overlaps_amphibian <- data.frame(overlaps_amphibian)

overlaps_bird <- array(NA, dim = c(length(unique(dsSPDF_bird@data$binomial)), 4))
colnames(overlaps_bird) <- c("Binomial", "NumberTypes", "NumberOverlaps", "PercentOverlaps")
overlaps_bird <- data.frame(overlaps_bird)

overlaps_mammal <- array(NA, dim = c(length(unique(dsSPDF_mammal@data$binomial)), 4))
colnames(overlaps_mammal) <- c("Binomial", "NumberTypes", "NumberOverlaps", "PercentOverlaps")
overlaps_mammal <- data.frame(overlaps_mammal)

# Loop through for each species
for (i in 1:length(unique(dsSPDF_amphibian@data$binomial))) {
  
  # Which species is species i?
  species_i <- as.character(unique(dsSPDF_amphibian@data$binomial)[i])
  # How many Types do we have for that species?
  no_types <- length(which(dsSPDF_amphibian@data$binomial == species_i))
  # Subset locality data so we just have locality for species i
  locality_i <- subset(dsSPDF_amphibian, dsSPDF_amphibian@data$binomial == species_i)
  # Subset map data so we just have map for species i
  map_i <- subset(maps_amphibian, maps_amphibian$binomial == species_i)
  # How many of the Type localities overlap with range polygons?
  no_overlaps <- sum(!is.na(over(locality_i, as(map_i, "SpatialPolygons"))))
  
  # Outputs
  # I have added the number and % of overlaps as some
  # species have > 1 type
  overlaps_amphibian[i, "Binomial"] <- species_i
  overlaps_amphibian[i, "NumberTypes"] <- no_types
  overlaps_amphibian[i, "NumberOverlaps"] <- no_overlaps
  overlaps_amphibian[i, "PercentOverlaps"] <- (no_overlaps/no_types) * 100
  
} # end loop

# Birds
# Loop through for each species
for (i in 1:length(unique(dsSPDF_bird@data$binomial))) {
  
  # Which species is species i?
  species_i <- as.character(unique(dsSPDF_bird@data$binomial)[i])
  # How many Types do we have for that species?
  no_types <- length(which(dsSPDF_bird@data$binomial == species_i))
  # Subset locality data so we just have locality for species i
  locality_i <- subset(dsSPDF_bird, dsSPDF_bird@data$binomial == species_i)
  # Subset map data so we just have map for species i
  map_i <- subset(maps_bird, maps_bird$binomial == species_i)
  # How many of the Type localities overlap with range polygons?
  no_overlaps <- sum(!is.na(over(locality_i, as(map_i, "SpatialPolygons"))))
  
  # Outputs
  # I have added the number and % of overlaps as some
  # species have > 1 type
  overlaps_bird[i, "Binomial"] <- species_i
  overlaps_bird[i, "NumberTypes"] <- no_types
  overlaps_bird[i, "NumberOverlaps"] <- no_overlaps
  overlaps_bird[i, "PercentOverlaps"] <- (no_overlaps/no_types) * 100
  
} # end loop

# Loop through for each species
for (i in 1:length(unique(dsSPDF_mammal@data$binomial))) {
  
  # Which species is species i?
  species_i <- as.character(unique(dsSPDF_mammal@data$binomial)[i])
  # How many Types do we have for that species?
  no_types <- length(which(dsSPDF_mammal@data$binomial == species_i))
  # Subset locality data so we just have locality for species i
  locality_i <- subset(dsSPDF_mammal, dsSPDF_mammal@data$binomial == species_i)
  # Subset map data so we just have map for species i
  map_i <- subset(maps_mammal, maps_mammal$binomial == species_i)
  # How many of the Type localities overlap with range polygons?
  no_overlaps <- sum(!is.na(over(locality_i, as(map_i, "SpatialPolygons"))))
  
  # Outputs
  # I have added the number and % of overlaps as some
  # species have > 1 type
  overlaps_mammal[i, "Binomial"] <- species_i
  overlaps_mammal[i, "NumberTypes"] <- no_types
  overlaps_mammal[i, "NumberOverlaps"] <- no_overlaps
  overlaps_mammal[i, "PercentOverlaps"] <- (no_overlaps/no_types) * 100
  
} # end loop

# Look at the output
overlaps_amphibian
overlaps_bird
overlaps_mammal

# Save output
write_csv(overlaps_amphibian, file = here("data/overlaps_amphibian"))
write_csv(overlaps_bird, file = here("data/overlaps_bird"))
write_csv(overlaps_mammal, file = here("data/overlaps_mammal"))
```
